id: P007093
initial_creation_type: ocr
source_metadata:
  id: bdr:W3CN5219
  title: མུན་སེལ་ཤེས་རབ་འོད་སྣང་།
  author: ''
  volumes:
    b8294e1af1f5417aaebf195d5f3214da:
      image_group_id: I3CN5221
      title: ''
      volume_number: 1
      total_pages: 214
ebook_metadata:
  title: མུན་སེལ་ཤེས་རབ་འོད་སྣང་།
  author: ''
  sku: P007093
  cover: cover.jpg
  layers:
  - pagination
