id: I5B94B9CB
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-30T23:52:13+00:00'
last_modified: '2022-06-09T04:48:16.012635+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W3CN5219
  title: མུན་སེལ་ཤེས་རབ་འོད་སྣང་།
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
  base:
    8BF8:
      image_group_id: I3CN5221
      title: Volume 1 of mun sel shes rab 'od snang /
      total_pages: 214
      order: 1
      base_file: 8BF8.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
